<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="7" passed="5" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-08-08T17:56:42 PDT" name="Default suite" finished-at="2022-08-08T17:56:51 PDT" duration-ms="8279">
    <groups>
    </groups>
    <test started-at="2022-08-08T17:56:42 PDT" name="Default test" finished-at="2022-08-08T17:56:51 PDT" duration-ms="8279">
      <class name="com.apex.api_Testcases.CustomerGETAPITestng">
        <test-method signature="testWithCorrecID(java.lang.String,java.lang.String)[pri:1, instance:com.apex.api_Testcases.CustomerGETAPITestng@6283d8b8]" started-at="2022-08-08T17:56:44 PDT" name="testWithCorrecID" data-provider="correctids_dp" finished-at="2022-08-08T17:56:45 PDT" duration-ms="1813" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[3996]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Shivakari Guneta]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testWithCorrecID -->
        <test-method signature="testWithCorrecID(java.lang.String,java.lang.String)[pri:1, instance:com.apex.api_Testcases.CustomerGETAPITestng@6283d8b8]" started-at="2022-08-08T17:56:45 PDT" name="testWithCorrecID" data-provider="correctids_dp" finished-at="2022-08-08T17:56:46 PDT" duration-ms="998" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[3995]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Bhadra Gupta V]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<200> but was:<404>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<200> but was:<404>
at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.failNotEquals(Assert.java:743)
at org.junit.Assert.assertEquals(Assert.java:118)
at org.junit.Assert.assertEquals(Assert.java:555)
at org.junit.Assert.assertEquals(Assert.java:542)
at com.apex.api_core.Validate.performBasicValidation(Validate.java:17)
at com.apex.api_Testcases.CustomerGETAPITestng.testWithCorrecID(CustomerGETAPITestng.java:33)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testWithCorrecID -->
        <test-method signature="testWithCorrecID(java.lang.String,java.lang.String)[pri:1, instance:com.apex.api_Testcases.CustomerGETAPITestng@6283d8b8]" started-at="2022-08-08T17:56:46 PDT" name="testWithCorrecID" data-provider="correctids_dp" finished-at="2022-08-08T17:56:47 PDT" duration-ms="920" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[4006]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Dulari Sinha JD]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<200> but was:<404>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<200> but was:<404>
at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.failNotEquals(Assert.java:743)
at org.junit.Assert.assertEquals(Assert.java:118)
at org.junit.Assert.assertEquals(Assert.java:555)
at org.junit.Assert.assertEquals(Assert.java:542)
at com.apex.api_core.Validate.performBasicValidation(Validate.java:17)
at com.apex.api_Testcases.CustomerGETAPITestng.testWithCorrecID(CustomerGETAPITestng.java:33)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testWithCorrecID -->
        <test-method signature="testWithCorrectData()[pri:3, instance:com.apex.api_Testcases.CustomerGETAPITestng@6283d8b8]" started-at="2022-08-08T17:56:47 PDT" name="testWithCorrectData" finished-at="2022-08-08T17:56:48 PDT" duration-ms="927" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testWithCorrectData -->
        <test-method signature="testWithCharacters()[pri:4, instance:com.apex.api_Testcases.CustomerGETAPITestng@6283d8b8]" started-at="2022-08-08T17:56:48 PDT" name="testWithCharacters" finished-at="2022-08-08T17:56:49 PDT" duration-ms="949" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testWithCharacters -->
        <test-method signature="testWithNegativeNumbers()[pri:5, instance:com.apex.api_Testcases.CustomerGETAPITestng@6283d8b8]" started-at="2022-08-08T17:56:49 PDT" name="testWithNegativeNumbers" finished-at="2022-08-08T17:56:50 PDT" duration-ms="966" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testWithNegativeNumbers -->
        <test-method signature="testWithLongNumbers()[pri:6, instance:com.apex.api_Testcases.CustomerGETAPITestng@6283d8b8]" started-at="2022-08-08T17:56:50 PDT" name="testWithLongNumbers" finished-at="2022-08-08T17:56:51 PDT" duration-ms="433" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testWithLongNumbers -->
      </class> <!-- com.apex.api_Testcases.CustomerGETAPITestng -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
